language: r
#os:
  #- osx
#cache: packages
sudo: false


before_install:
  - tlmgr update --self --all
  - tlmgr install listings

r_packages:
  - survival

addons:
  apt:
    packages:
      - tcl-dev
      - tk-dev
      - texlive-latex-extra
      
warnings_are_errors: false
